# Generated by Django 5.0.2 on 2024-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uuid',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True),
        ),
    ]
