# Generated by Django 5.0.2 on 2024-03-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_favorite_book_is_read_book_user'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.category'),
            preserve_default=False,
        ),
    ]
