# Generated by Django 5.0.2 on 2024-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otptoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='tp_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='otptoken',
            old_name='otp_expires_at',
            new_name='expires_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='46da42', max_length=6),
        ),
    ]
