# Generated by Django 5.0.2 on 2024-03-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.AddField(
            model_name='otptoken',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='18251e', max_length=6),
        ),
    ]
