# Generated by Django 5.0.2 on 2024-03-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_otptoken_user_otptoken_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='33549c', max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
