# Generated by Django 5.0.2 on 2024-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_otptoken_otp_code_alter_otptoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
